name: Gatsby Publish

on: [push]

jobs:
  buil1d:
    runs-on: ubuntu-latest
    steps:
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
